### ISSUE TITLE
error will sending sms

### ISSUE THREAD

**Issue by termux4me** [p4kl0nc4t/Spammer-Grab#15]
Traceback (most recent call last):
  File "spammer.py", line 82, in <module>
    main()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "spammer.py", line 38, in main
    res, reason, wait = send_gac_req(phone_num, country_code)
  File "spammer.py", line 72, in send_gac_req
    raise NotImplementedError(
NotImplementedError: something went wrong, please submit an issue.

**Comment by V1thx** [comment]
Same, still doesnt found any solution.

**Comment by AleyKottur** [comment]
Oh... I already broke my whole brain while I was deciding ... I didn't decide
