### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by zer-far** [p4kl0nc4t/Spammer-Grab#26]
I ran `python spammer.py 44##########` and this error came:

Traceback (most recent call last):
  File "/home/pc/Desktop/Spammer-Grab/spammer.py", line 82, in <module>
    main()
  File "/home/pc/.local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pc/.local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pc/.local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pc/.local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pc/Desktop/Spammer-Grab/spammer.py", line 38, in main
    res, reason, wait = send_gac_req(phone_num, country_code)
  File "/home/pc/Desktop/Spammer-Grab/spammer.py", line 72, in send_gac_req
    raise NotImplementedError(
NotImplementedError: something went wrong, please submit an issue.

**Comment by dlslater36** [comment]
Having same issue, same errors everything
