### ISSUE TITLE
New Issues

### ISSUE THREAD

**Issue by zeeebbbrrraaa** [p4kl0nc4t/Spammer-Grab#6]
python spammer.py 6287876368252 -dl 2 -li 10                        spammer.py — Grab Activation Code (GAC) spammer
 author loncat <me@lcat.dev>
 url    https://github.com/p4kl0nc4t/Spammer-Grab

-- phone number: 628*****6**52, country code: ID
Traceback (most recent call last):
  File "spammer.py", line 82, in <module>
    main()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)                      File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)                                    File "spammer.py", line 38, in main
    res, reason, wait = send_gac_req(phone_num, country_code)
  File "spammer.py", line 73, in send_gac_req                             'something went wrong, please submit an issue.')
NotImplementedError: something went wrong, please submit an issue.

**Comment by p4kl0nc4t** [comment]
Will check on that later. Any kind of help is appreciated.

**Comment by EulerIExponent** [comment]
> Will check on that later. Any kind of help is appreciated.

This happens because ,exceptions are defined for status code 429 and 200 .If it produces any other status code like 404 or 403 (means network error or site is banned in that country) it produces NotImplementedError because tool author not defined it so check which status code it is giving and then impliment the solution adding proxy option along with tor browser may work

**Comment by p4kl0nc4t** [comment]
Still doesn't work on me too. Will try to find a solution.

**Comment by termux4me** [comment]
i believe the api doesn't work anymore

**Comment by termux4me** [comment]
click.echo(req.status_code)
got an
404 error

**Comment by oceannco** [comment]
It still not working. Did you find a solution?

**Comment by rgeorge04** [comment]
Doesn't work for me

**Comment by p4kl0nc4t** [comment]
# Attention
I apologize for the slow response. I have investigated the problem and found that the API endpoint used in Spammer-Grab is no longer working. Therefore, Spammer-Grab will not work until a new working API is discovered.
## Call for contribution
Anyone who could or have discovered the new API endpoint through reverse-engineering or any other method can help contribute to this project by sending a pull request or just by replying to this comment with the details of the endpoint.

**Comment by EulerIExponent** [comment]
Instead you should find api endpoint of multiple websites .As this tool is public using single api endpoint is not good idea also if you provide proxy option it may lead to ip bab .So considering privacy of users you should add multiple api endpoints and proxy option also there are many github projects => good source as reference .Also try to use any other module instead of requests,you can use any asynchronous module for better performance or you can rewrite tool in php .
(you can use endpoint of amazon,truecaller,instagram,facebook,twitter like websites for sms spamming if account exist then use forgot password method if not exists then create account so you get sms )

**Comment by p4kl0nc4t** [comment]
That's a nice idea. I will consider making a new repo for that "spam"
framework. I think it would be nice to have a modular one.

This repo is for Spammer-Grab. Therefore, it should only contain Grab APIs.
I agree that this is not a good idea. But, let's not forget the main idea
of the project.

Stay tuned, now I am really thinking about making your idea.
