### ISSUE TITLE
Still wont work

### ISSUE THREAD

**Issue by haxersworld** [p4kl0nc4t/Spammer-Grab#9]
Traceback (most recent call last):
  File "spammer.py", line 82, in <module>
    main()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "spammer.py", line 38, in main
    res, reason, wait = send_gac_req(phone_num, country_code)
  File "spammer.py", line 73, in send_gac_req
    'something went wrong, please submit an issue.')
NotImplementedError: something went wrong, please submit an issue.

**Comment by p4kl0nc4t** [comment]
https://github.com/p4kl0nc4t/Spammer-Grab/issues/6
